// <auto-generated />
using System;
using System.Diagnostics;
using System.Security.Permissions;
using Microsoft.Office.Tools;
using Microsoft.Office.Tools.Word;
using Microsoft.VisualStudio.Tools.Applications.Runtime;
using Word = Microsoft.Office.Interop.Word;

namespace FormulaBridge.WordAddIn
{
    [StartupObject(0)]
    [PermissionSet(SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : AddInBase
    {
        internal Word.Application Application;

        [DebuggerNonUserCode]
        public ThisAddIn(ApplicationFactory factory, IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
        }

        [DebuggerNonUserCode]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Word.Application>(typeof(Word.Application), "Application");
        }

        [DebuggerNonUserCode]
        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        [DebuggerNonUserCode]
        protected override void OnShutdown()
        {
            Application = null;
            base.OnShutdown();
        }
    }
}
